import { PlayBoardSoT, ScreenRegistry, WorkItemRegistry, ControlAreaRegistry, FlowRegistry } from './models';

export const PLAYBOARD_DATA: PlayBoardSoT = {
  planes: ['end-user', 'system-state'],
  phaseOrder: ['Phase 1: Setup', 'Phase 2: UI', 'Phase 3: Logic', 'Phase 4: Launch'],
  statusOrder: ['미착수', '부분구현', '구현·머지완료', '검증완료'],
  day1Anchor: '2026-06-25',

  screens: [
    {
      plane: 'end-user',
      slug: 'chat',
      title: '메인 채팅 화면',
      route: '/',
      designSpecType: '서비스형',
      flowNote: '사용자가 챗봇과 대화하며 조언을 얻는 주 진입점',
      status: '부분구현',
      workItems: ['task-2', 'task-3'],
      requirementRefs: ['Notion MVP 가이드'],
      implLocation: 'src/screens/ChatScreen.tsx',
      engineering: {
        authGate: '없음 (MVP 한정 로컬 단말기 기반)',
        clientActions: ['메시지 입력', '서버 스트리밍 수신', '로컬 Fallback 렌더링'],
        serverActions: ['OpenAI gpt-4o-mini 호출', 'Tavily Search 연동'],
        dataReads: ['Supabase Profile (예정)'],
        dataWrites: ['Heritage Logs 저장 (예정)'],
        telemetryEvents: ['채팅 시작', '검색 수행'],
        exceptionStates: ['fallback-error'],
        controlAreaNotes: {
          performance: '스트리밍 3초 내 시작 확인 요망',
          compliance: '자문법 필터링 정규식 엣지 펑션 탑재',
          cost: '키 미존재 시 로컬 Fallback 위로 반환 처리',
          ux: '잠금/블러 전면 배제, 네이티브 키보드 회피',
        },
      },
    },
    {
      plane: 'system-state',
      slug: 'fallback-error',
      title: '로컬 폴백 응답',
      route: 'N/A (인라인 응답)',
      designSpecType: '상태형',
      flowNote: '네트워크 단절 또는 API 키 부족 시 표시',
      status: '구현·머지완료',
      workItems: ['task-6'],
      requirementRefs: ['NFR-003 비용 한도 및 장애 대응'],
      implLocation: 'src/screens/ChatScreen.tsx (catch block)',
      engineering: {
        authGate: 'N/A',
        clientActions: ['로컬 메시지 렌더링'],
        serverActions: [],
        dataReads: [],
        dataWrites: [],
        telemetryEvents: [],
        exceptionStates: [],
        controlAreaNotes: {
          cost: '외부망 단절에도 작동 보장',
          ux: '이질감 없이 자연스러운 텍스트로 처리',
        },
      },
    },
  ],

  workItems: [
    {
      id: 'task-1',
      title: '프론트엔드 환경 셋업 (Expo)',
      phase: 'Phase 1: Setup',
      status: '완료',
      dependsOn: [],
      screens: [],
      doc: 'task.md 참조',
    },
    {
      id: 'task-2',
      title: 'ChatScreen UI 컴포넌트 개발',
      phase: 'Phase 2: UI',
      status: '완료',
      dependsOn: ['task-1'],
      screens: ['end-user/chat'],
      doc: 'GiftedChat 연동',
    },
    {
      id: 'task-3',
      title: 'LLM 스트리밍 연동 (Edge Function)',
      phase: 'Phase 3: Logic',
      status: '리뷰대기', // '리뷰대기' means partial / PR ready
      dependsOn: ['task-2'],
      screens: ['end-user/chat'],
      doc: 'supabase/functions/chat/index.ts',
    },
    {
      id: 'task-4',
      title: '웹 검색 연동 (Tavily)',
      phase: 'Phase 3: Logic',
      status: '미착수',
      dependsOn: ['task-3'],
      screens: ['end-user/chat'],
      doc: 'Tavily API 연결',
    },
    {
      id: 'task-5',
      title: '마스킹 규칙 (Compliance) 적용',
      phase: 'Phase 4: Launch',
      status: '미착수',
      dependsOn: ['task-3'],
      screens: ['end-user/chat'],
      doc: '정규식 필터링 탑재',
    },
    {
      id: 'task-6',
      title: '로컬 Fallback 예외 처리',
      phase: 'Phase 3: Logic',
      status: '완료',
      dependsOn: ['task-2'],
      screens: ['system-state/fallback-error'],
      doc: 'catch block에서 처리',
    },
  ],

  controlAreas: [
    {
      area: 'performance',
      goal: '스트리밍 응답 3초 내 개시',
      summary: '사용자 체감 속도 향상을 위해 SSE 스트리밍을 통한 첫 바이트 도달 시간 보장.',
      policies: [{ statement: '모든 AI 응답은 스트리밍 필수', detail: 'Edge Function에서 Response Body로 ReadableStream 전달' }],
      decisions: [{ name: 'LLM Timeout', value: '2500ms' }],
      standards: [],
      workItems: ['task-3'],
      gaps: [],
    },
    {
      area: 'compliance',
      goal: '투자 자문법 위반 원천 차단',
      summary: '단정적 종목 추천이나 수익률 보장 발언을 마스킹하여 법적 리스크 해소.',
      policies: [{ statement: '정규식을 통한 실시간 마스킹', detail: '[규제 마스킹] 으로 스트리밍 청크 대체' }],
      decisions: [{ name: '위험 키워드', value: '무조건 매수, 수익률 보장 등' }],
      standards: [],
      workItems: ['task-5'],
      gaps: ['아직 마스킹 정규식이 Edge Function에 완벽히 적용되지 않음'],
    },
    {
      area: 'cost',
      goal: '월 예산 80% 소진 방어',
      summary: '무거운 Tool Calling이 예산을 초과하지 않도록 억제.',
      policies: [{ statement: '예산 초과 시 로컬 위로 Fallback', detail: '비용 소진 후엔 API 호출 원천 차단' }],
      decisions: [{ name: '1인 월 예산 한도', value: '1,000원' }],
      standards: [],
      workItems: ['task-6'],
      gaps: [],
    },
    {
      area: 'ux',
      goal: '비강압적 무한 교감',
      summary: '사용자 흐름을 인위적으로 막는 블러, 모달 팝업 배제.',
      policies: [{ statement: '블러링/강제 모달 전면 배제', detail: '화면 이탈을 자유롭게 허용' }],
      decisions: [],
      standards: [],
      workItems: ['task-2'],
      gaps: [],
    },
  ],

  flows: [
    {
      id: 'main-chat',
      title: '메인 교감 시나리오',
      description: '사용자가 앱에 진입해 Vesper와 대화하는 흐름',
      plane: 'end-user',
      screens: ['end-user/chat'],
      isSequential: true,
    },
    {
      id: 'fallback',
      title: '예외: 통신 장애 및 예산 소진',
      description: '서버 접속 불가 시 발생하는 로컬 대체 흐름',
      plane: 'system-state',
      screens: ['system-state/fallback-error'],
      isSequential: false,
    },
  ],
};
